disable_existing_loggers: false
formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(lineno)d - %(message)s'
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(filename)s %(lineno)s %(message)s'
  simple:
    format: '%(levelname)s - %(message)s'
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: CUST_TRACE
  file_debug:
    class: logging.FileHandler
    filename: debug.log
    formatter: detailed
    level: DEBUG
  # file_error:
  #   class: logging.FileHandler
  #   filename: error.log
  #   formatter: detailed
  #   level: ERROR
  file_info:
    class: logging.FileHandler
    filename: info.log
    formatter: json
    level: CUST_TRACE
  file_query:
    class: logging.FileHandler
    filename: query.log
    formatter: json
    level: QUERY
loggers:
  '': 
    handlers:
      - console
      - file_info
      - file_query
      - file_debug
    level: CUST_TRACE
version: 1
