FlirItsSummarySpeedPerZoneEventType:
  agg_dict:
    avgSpeed: mean
    counter: sum
  drop_columns: null
  duplicate_filter_columns:
  - timestamp
  - type
  - direction
  - locationName
  - SID
  meta_columns:
  - lat
  - lon
  - SID
  - upHash
  - _headers.eventType
  - type
  - direction
  rename_columns: null
  timestamp_columns:
  - timestamp
MunisenseNoiseEventType:
  agg_dict:
    laeqMaxValue: max
    laeqMinValue: min
    laeqValue: mean
    lasMaxValue: max
    lcPeakValue: max
    lceqValue: mean
    lcsMaxValue: max
  drop_columns: null
  duplicate_filter_columns: null
  meta_columns:
  - lat
  - lon
  - SID
  - upHash
  - _headers.eventType
  - deviceId
  rename_columns: null
  timestamp_columns:
  - timestamp
  - laeqTimestamp
  - lasMaxTimestamp
  - lceqTimestamp
  - laeqMinTimestamp
  - laeqMaxTimestamp
  - lcPeakTimestamp
  - lcsMaxTimestamp
OpenWeatherMapEventType:
  agg_dict:
    clouds: avg
    grnd_level: avg
    humidity: avg
    pressure: avg
    sea_level: avg
    temp: avg
    visibility: avg
    wind_deg: avg
    wind_speed: avg
  drop_columns:
  - weather_id
  - weather_icon
  - temp_max
  - temp_min
  - feels_like
  - esGeoLocation
  duplicate_filter_columns: null
  meta_columns:
  - _headers_eventType
  rename_columns:
    #temp: temp
  timestamp_columns:
  - timestamp
  - sunrise
  - sunset
  group_columns:
    timestamp:
      dtype: None
      interval: 1h
    SID:
      dtype: string
    lat:
      dtype: float
    lon:
      dtype: float
SensoterraGroundMoistureEventType:
  agg_dict:
    batteryVoltage: max
    sensorDepth: mean
    signalPower: mean
    signalStrength: max
    temperature: mean
    volumetricSoilMoisture: mean
  drop_columns:
  - id
  - esGeoLocation
  duplicate_filter_columns: null
  meta_columns:
  - lat
  - lon
  - SID
  - upHash
  - _headers.eventType
  rename_columns: null
  timestamp_columns:
  - timestamp
